### ISSUE TITLE
Crear una vista en flask

### ISSUE THREAD

**Issue by gianfranco-s** [Ramiro-Dubini/atendi#1]
Para empezar a migrar el código que tienen a Flask, les recomiendo que hagan un "Hello, world", que consiste en levantar un servidor local y mostrar un sitio en html que diga "Hello, world" o un mensaje igualmente inspirador.

**Comment by gianfranco-s** [comment]
Para hacerlo en GitHub, creen una rama

```
git checkout -b 1_crear_vista_base
```

Commitean los cambios, los suben al repo
```
git push -u origin 1_crear_vista_base
```

Una vez que todo está funcionando en la rama, crean un [Pull Request](https://github.com/Ramiro-Dubini/atendi/pulls)

Y después le podemos hacer un review

**Comment by franpuricelli** [comment]
> Para empezar a migrar el código que tienen a Flask, les recomiendo que hagan un "Hello, world", que consiste en levantar un servidor local y mostrar un sitio en html que diga "Hello, world" o un mensaje igualmente inspirador.

https://vercel.com/templates/python/flask-hello-world
